<? 
/* *******************************************************************************************************
MODUL NAME 			: MTSN LAWANG
FILE NAME 			: 
AUTHOR				: 
VERSION				: 1.0
MODIFICATION DOC	:
DESCRIPTION			: 
***************************************************************************************************** */

/***
* Entity-base class untuk mengimplementasikan tabel kategori.
* 
***/
include_once(APPPATH.'/models/Entity.php');

class AbsensiRekap extends Entity{ 

	var $query;
	var $id;

	/**
	* Class constructor.
	**/
	function AbsensiRekap()
	{
	  $this->Entity(); 
	}


	function setPartisiTablePeriode($periode)
	{
		$str = "SELECT presensi.PARTISITABLE('".$periode."') AS ROWCOUNT "; 
		$this->query = $str;
		$this->select($str);
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return ""; 
    }

	function getDataAbsensiPeriode($periode, $statement)
	{
		$str = "SELECT partisi.GETDATAABSENSIPERIODE('".$periode."', '".$statement."') AS ROWCOUNT "; 
		$this->query = $str;
		$this->select($str);
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return ""; 
    }

	function selectByParamsPegawai($paramsArray=array(),$limit=-1,$from=-1, $statement='', $order=' ORDER BY A.KODE')
	{
		$str = "
		SELECT 
			A.PEGAWAI_ID, A.NIP_BARU, A.NAMA_LENGKAP
			, AMBIL_SATKER_NAMA_DYNAMIC(A.SATUAN_KERJA_ID) SATUAN_KERJA_NAMA, AMBIL_SATKER_INDUK(A.SATUAN_KERJA_ID) SATUAN_KERJA_INDUK
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		WHERE 1 = 1
		"; 
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		// echo $str;exit();
		return $this->selectLimit($str,$limit,$from);
	}

	function getCountByParamsPegawai($paramsArray=array(), $statement='')
	{
		$str = "
		SELECT COUNT(1) AS ROWCOUNT 
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		WHERE 1 = 1 ".$statement;
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		$this->query = $str;
		// echo $str;exit();
		$this->select($str); 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0;  
	}

	function selectByParamsRekap($paramsArray=array(),$limit=-1,$from=-1, $periode, $statement='', $order=' ORDER BY A.KODE')
	{
		$str = "
		SELECT 
			A.PEGAWAI_ID, A.NIP_BARU, A.NAMA_LENGKAP
			, AMBIL_SATKER_NAMA_DYNAMIC(A.SATUAN_KERJA_ID) SATUAN_KERJA_NAMA, AMBIL_SATKER_INDUK(A.SATUAN_KERJA_ID) SATUAN_KERJA_INDUK
			, PERIODE, IN_1, OUT_1, JJ_1, IN_2,
			OUT_2, JJ_2, IN_3, OUT_3, JJ_3, IN_4, OUT_4, JJ_4, IN_5,
			OUT_5, JJ_5, IN_6, OUT_6, JJ_6, IN_7, OUT_7, JJ_7, IN_8,
			OUT_8, JJ_8, IN_9, OUT_9, JJ_9, IN_10, OUT_10, JJ_10, IN_11,
			OUT_11, JJ_11, IN_12, OUT_12, JJ_12, IN_13, OUT_13, JJ_13,
			IN_14, OUT_14, JJ_14, IN_15, OUT_15, JJ_15, IN_16, OUT_16,
			JJ_16, IN_17, OUT_17, JJ_17, IN_18, OUT_18, JJ_18, IN_19,
			OUT_19, JJ_19, IN_20, OUT_20, JJ_20, IN_21, OUT_21, JJ_21,
			IN_22, OUT_22, JJ_22, IN_23, OUT_23, JJ_23, IN_24, OUT_24,
			JJ_24, IN_25, OUT_25, JJ_25, IN_26, OUT_26, JJ_26, IN_27,
			OUT_27, JJ_27, IN_28, OUT_28, JJ_28, IN_29, OUT_29, JJ_29,
			IN_30, OUT_30, JJ_30, IN_31, OUT_31, JJ_31
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		LEFT JOIN (SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('".$periode."', '')) B ON A.PEGAWAI_ID = CAST(B.PEGAWAI_ID AS NUMERIC)
		WHERE 1 = 1
		"; 
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		// echo $str;exit();
		return $this->selectLimit($str,$limit,$from);
	}

	function getCountByParamsRekap($paramsArray=array(), $periode, $statement='')
	{
		$str = "
		SELECT COUNT(1) AS ROWCOUNT 
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		LEFT JOIN (SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('".$periode."', '')) B ON A.PEGAWAI_ID = CAST(B.PEGAWAI_ID AS NUMERIC)
		WHERE 1 = 1 ".$statement;
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		$this->query = $str;
		// echo $str;exit();
		$this->select($str); 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0;  
	}

	function selectByParamsRekapJamKerja($paramsArray=array(),$limit=-1,$from=-1, $periode, $statement='', $order=' ORDER BY A.KODE')
	{
		$str = "
		SELECT 
			A.PEGAWAI_ID, A.NIP_BARU, A.NAMA_LENGKAP
			, AMBIL_SATKER_NAMA_DYNAMIC(A.SATUAN_KERJA_ID) SATUAN_KERJA_NAMA, AMBIL_SATKER_INDUK(A.SATUAN_KERJA_ID) SATUAN_KERJA_INDUK
			, PERIODE, IN_1, OUT_1, JJ_1, IN_2,
			OUT_2, JJ_2, IN_3, OUT_3, JJ_3, IN_4, OUT_4, JJ_4, IN_5,
			OUT_5, JJ_5, IN_6, OUT_6, JJ_6, IN_7, OUT_7, JJ_7, IN_8,
			OUT_8, JJ_8, IN_9, OUT_9, JJ_9, IN_10, OUT_10, JJ_10, IN_11,
			OUT_11, JJ_11, IN_12, OUT_12, JJ_12, IN_13, OUT_13, JJ_13,
			IN_14, OUT_14, JJ_14, IN_15, OUT_15, JJ_15, IN_16, OUT_16,
			JJ_16, IN_17, OUT_17, JJ_17, IN_18, OUT_18, JJ_18, IN_19,
			OUT_19, JJ_19, IN_20, OUT_20, JJ_20, IN_21, OUT_21, JJ_21,
			IN_22, OUT_22, JJ_22, IN_23, OUT_23, JJ_23, IN_24, OUT_24,
			JJ_24, IN_25, OUT_25, JJ_25, IN_26, OUT_26, JJ_26, IN_27,
			OUT_27, JJ_27, IN_28, OUT_28, JJ_28, IN_29, OUT_29, JJ_29,
			IN_30, OUT_30, JJ_30, IN_31, OUT_31, JJ_31
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		LEFT JOIN (SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('".$periode."', '')) B ON A.PEGAWAI_ID = CAST(B.PEGAWAI_ID AS NUMERIC)
		WHERE 1 = 1
		"; 
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		return $this->selectLimit($str,$limit,$from);
	}

	function getCountByParamsRekapJamKerja($paramsArray=array(), $periode, $statement='')
	{
		$str = "
		SELECT COUNT(1) AS ROWCOUNT 
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		LEFT JOIN (SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('".$periode."', '')) B ON A.PEGAWAI_ID = CAST(B.PEGAWAI_ID AS NUMERIC)
		WHERE 1 = 1 ".$statement;
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		$this->query = $str;
		$this->select($str); 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0;  
	}

	function selectByParamsReviewPresensi($paramsArray=array(),$limit=-1,$from=-1, $statement="", $pegawaiid, $periode, $order=" ORDER BY A.HARI ASC")
	{
		$str = "
		SELECT
		A.PEGAWAI_ID, A.PERIODE, A.MASUK, A.MASUK_KETERANGAN, A.JAM_MASUK
		, A.JAM_PULANG, SPLIT_PART(A.AUTH_MASUK, '#', 1) AUTH_MASUK, SPLIT_PART(A.AUTH_PULANG, '#', 1) AUTH_PULANG
		, NULL LOKASI_AUTH_MASUK, NULL LOKASI_AUTH_PULANG
		, A.HARI, A.TANGGAL, A.NAMA_HARI, A.TERLAMBAT, A.PULANG_CEPAT
		, 
		CASE 
			WHEN A.JAM_MASUK IS NULL THEN NULL
			WHEN (A.JAM_MASUK::INTERVAL - '07:30'::INTERVAL) < '00:00:00' THEN NULL
			WHEN (A.JAM_MASUK::INTERVAL - '07:30'::INTERVAL) < '00:15:00' THEN TO_NUMBER(TO_CHAR((A.JAM_MASUK::INTERVAL - '07:30'::INTERVAL), 'MI'), '99') ||' mnt'
			ELSE 15||' mnt' 
		END TIDAK_DIPOTONG
		,
		CASE 
			WHEN MASUK like 'efektif-LA%' THEN 'Lupa Check Log'
			WHEN MASUK not like 'efektif%' THEN MASUK_KETERANGAN
			ELSE NULL
		END KETERANGAN
		, NULL JAM_MASUK_LEMBUR, NULL JAM_PULANG_LEMBUR, NULL KETERANGAN_LEMBUR
		, JAM_SHIFT, NULL JUMLAH_TERLAMBAT, A.STATUS_MASUK
		FROM 
		(
			SELECT 
			A.PEGAWAI_ID, A.PERIODE, A.MASUK, A.MASUK_KETERANGAN,
			A.JAM_MASUK, A.JAM_PULANG, A.HARI, A.TANGGAL, A.NAMA_HARI,
			B.TERLAMBAT, B.PULANG_CEPAT, B.AUTH_MASUK, B.AUTH_PULANG, JAM_SHIFT,
			B.MASUK STATUS_MASUK
			FROM (SELECT * FROM presensi.P_REKAP_KEHADIRAN_TANGGAL('".$periode."', ' AND A.PEGAWAI_ID = ''''".$pegawaiid."'''' ')) A 
			LEFT JOIN (SELECT * FROM presensi.P_REKAP_KEHADIRAN_V2('".$periode."', ' AND A.PEGAWAI_ID = ''".$pegawaiid."'' ')) B ON A.HARI = B.HARI
		) A
		WHERE 1=1
		"; 
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		// echo $str;exit();
		return $this->selectLimit($str,$limit,$from);
	}

	function getCountByParamsReviewPresensi($paramsArray=array(), $statement='', $pegawaiid, $periode)
	{
		$str = "
		SELECT COUNT(1) AS ROWCOUNT 
		FROM 
		(
			SELECT 
			A.PEGAWAI_ID, A.PERIODE, A.MASUK, A.MASUK_KETERANGAN,
			A.JAM_MASUK, A.JAM_PULANG, A.HARI, A.TANGGAL, A.NAMA_HARI,
			B.TERLAMBAT, B.PULANG_CEPAT, B.AUTH_MASUK, B.AUTH_PULANG, JAM_SHIFT,
			B.MASUK STATUS_MASUK
			FROM (SELECT * FROM presensi.P_REKAP_KEHADIRAN_TANGGAL('".$periode."', ' AND A.PEGAWAI_ID = ''''".$pegawaiid."'''' ')) A 
			LEFT JOIN (SELECT * FROM presensi.P_REKAP_KEHADIRAN_V2('".$periode."', ' AND A.PEGAWAI_ID = ''".$pegawaiid."'' ')) B ON A.HARI = B.HARI
		) A
		WHERE 1 = 1 ".$statement;
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		$this->query = $str;
		// echo $str;exit();
		$this->select($str); 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0;  
	}

	function getCountByParamsInformasiRekapKehadiranTanggal($paramsArray=array(), $statement="", $pegawaiid, $periode)
	{
		$str = "
		SELECT COUNT(1) ROWCOUNT
		FROM (SELECT * FROM presensi.P_REKAP_KEHADIRAN_TANGGAL('".$periode."', ' AND A.PEGAWAI_ID = ''''".$pegawaiid."'''' ')) A
		WHERE 1 = 1 ".$statement; 
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		
		$this->query = $str;
		// echo $str;exit();
		$this->select($str); 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0; 
    }	

    function selectByParamsRekapRankingJamKerja($paramsArray=array(),$limit=-1,$from=-1, $periode, $statement='', $order=' ORDER BY A.KODE')
	{
		$str = "
		SELECT 
			A.PEGAWAI_ID, A.NIP_BARU, A.NAMA_LENGKAP
			, AMBIL_SATKER_NAMA_DYNAMIC(A.SATUAN_KERJA_ID) SATUAN_KERJA_NAMA, AMBIL_SATKER_INDUK(A.SATUAN_KERJA_ID) SATUAN_KERJA_INDUK
			, PERIODE, IN_1, OUT_1, JJ_1, IN_2,
			OUT_2, JJ_2, IN_3, OUT_3, JJ_3, IN_4, OUT_4, JJ_4, IN_5,
			OUT_5, JJ_5, IN_6, OUT_6, JJ_6, IN_7, OUT_7, JJ_7, IN_8,
			OUT_8, JJ_8, IN_9, OUT_9, JJ_9, IN_10, OUT_10, JJ_10, IN_11,
			OUT_11, JJ_11, IN_12, OUT_12, JJ_12, IN_13, OUT_13, JJ_13,
			IN_14, OUT_14, JJ_14, IN_15, OUT_15, JJ_15, IN_16, OUT_16,
			JJ_16, IN_17, OUT_17, JJ_17, IN_18, OUT_18, JJ_18, IN_19,
			OUT_19, JJ_19, IN_20, OUT_20, JJ_20, IN_21, OUT_21, JJ_21,
			IN_22, OUT_22, JJ_22, IN_23, OUT_23, JJ_23, IN_24, OUT_24,
			JJ_24, IN_25, OUT_25, JJ_25, IN_26, OUT_26, JJ_26, IN_27,
			OUT_27, JJ_27, IN_28, OUT_28, JJ_28, IN_29, OUT_29, JJ_29,
			IN_30, OUT_30, JJ_30, IN_31, OUT_31, JJ_31
			, TOTAL_JUMLAH_JAM
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		INNER JOIN (SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('".$periode."', '')) B ON A.PEGAWAI_ID = CAST(B.PEGAWAI_ID AS NUMERIC)
		WHERE 1 = 1
		"; 
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		return $this->selectLimit($str,$limit,$from);
	}

	function getCountByParamsRekapRankingJamKerja($paramsArray=array(), $periode, $statement='')
	{
		$str = "
		SELECT COUNT(1) AS ROWCOUNT 
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		INNER JOIN (SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('".$periode."', '')) B ON A.PEGAWAI_ID = CAST(B.PEGAWAI_ID AS NUMERIC)
		WHERE 1 = 1 ".$statement;
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		$this->query = $str;
		$this->select($str); 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0;  
	}

	function selectByParamsTotalJamKerjaTahun($paramsArray=array(),$limit=-1,$from=-1, $tahun, $statement='', $order=" ORDER BY COALESCE (BLN_01 + BLN_02 + BLN_03 + BLN_04 + BLN_05 + BLN_06 + BLN_07 + BLN_08 + BLN_09 + BLN_10 + BLN_11 + BLN_12, '00:00:00' :: INTERVAL ) DESC")
	{
		$str = "
		SELECT 
		A.PEGAWAI_ID, A.NIP_BARU, A.NAMA_LENGKAP
		, AMBIL_SATKER_NAMA_DYNAMIC(A.SATUAN_KERJA_ID) SATUAN_KERJA_NAMA, AMBIL_SATKER_INDUK(A.SATUAN_KERJA_ID) SATUAN_KERJA_INDUK
		, COALESCE (BLN_01, '00:00:00' :: INTERVAL ) BLN_01
		, COALESCE (BLN_02, '00:00:00' :: INTERVAL ) BLN_02
		, COALESCE (BLN_03, '00:00:00' :: INTERVAL ) BLN_03
		, COALESCE (BLN_04, '00:00:00' :: INTERVAL ) BLN_04
		, COALESCE (BLN_05, '00:00:00' :: INTERVAL ) BLN_05
		, COALESCE (BLN_06, '00:00:00' :: INTERVAL ) BLN_06
		, COALESCE (BLN_07, '00:00:00' :: INTERVAL ) BLN_07
		, COALESCE (BLN_08, '00:00:00' :: INTERVAL ) BLN_08
		, COALESCE (BLN_09, '00:00:00' :: INTERVAL ) BLN_09
		, COALESCE (BLN_10, '00:00:00' :: INTERVAL ) BLN_10
		, COALESCE (BLN_11, '00:00:00' :: INTERVAL ) BLN_11
		, COALESCE (BLN_12, '00:00:00' :: INTERVAL ) BLN_12
		, COALESCE (BLN_01 + BLN_02 + BLN_03 + BLN_04 + BLN_05 + BLN_06 + BLN_07 + BLN_08 + BLN_09 + BLN_10 + BLN_11 + BLN_12, '00:00:00' :: INTERVAL ) JUMLAH 
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		LEFT JOIN
		(
			SELECT 
				A.PEGAWAI_ID,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '01' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_01,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '02' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_02,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '03' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_03,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '04' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_04,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '05' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_05,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '06' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_06,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '07' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_07,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '08' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_08,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '09' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_09,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '10' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_10,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '11' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_11,
				COALESCE(SUM(CASE WHEN SUBSTR(PERIODE, 1, 2) = '12' THEN TOTAL_JUMLAH_JAM END), '00:00:00'::INTERVAL) BLN_12
			FROM 
			(
				SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('11".$tahun."', '')
				UNION ALL
				SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('12".$tahun."', '')
			) A
			GROUP BY A.PEGAWAI_ID
		) B ON A.PEGAWAI_ID = CAST(B.PEGAWAI_ID AS NUMERIC)
		WHERE 1=1
		"; 

		/*SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('012019', '')
		UNION ALL
		SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('022019', '')
		UNION ALL
		SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('032019', '')
		UNION ALL
		SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('042019', '')
		UNION ALL
		SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('052019', '')
		UNION ALL
		SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('062019', '')
		UNION ALL
		SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('072019', '')
		UNION ALL
		SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('08019', '')
		UNION ALL
		SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('092019', '')
		UNION ALL
		SELECT * FROM presensi.P_ABSENSI_REKAP_JAM_KERJA_V2('102019', '')
		UNION ALL*/
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		return $this->selectLimit($str,$limit,$from);
	}

	function getCountByParamsTotalJamKerjaTahun($paramsArray=array(), $tahun, $statement='')
	{
		$str = "
		SELECT COUNT(1) AS ROWCOUNT 
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		WHERE 1 = 1 ".$statement;
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		$this->query = $str;
		$this->select($str); 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0;  
	}

	function selectByParamsRekapTerlambatPulangKoreksi($paramsArray=array(),$limit=-1,$from=-1, $periode, $statement='', $order=' ')
	{
		$str = "
		SELECT 
			A.PEGAWAI_ID, A.NIP_BARU, A.NAMA_LENGKAP
			, AMBIL_SATKER_NAMA_DYNAMIC(A.SATUAN_KERJA_ID) SATUAN_KERJA_NAMA, AMBIL_SATKER_INDUK(A.SATUAN_KERJA_ID) SATUAN_KERJA_INDUK
			, COALESCE(KELOMPOK, '5H') KELOMPOK
			, (H + HT + HPC + HTPC) JUMLAH_H, (HT + HTPC) JUMLAH_HT
			, presensi.AMBIL_HARI_TERLAMBAT_KOREKSI(CAST(A.PEGAWAI_ID AS CHARACTER VARYING), '".$periode."') HT
			, (HPC + HTPC) JUMLAH_HPC, presensi.AMBIL_HARI_PLG_CEPAT_KOREKSI(CAST(A.PEGAWAI_ID AS CHARACTER VARYING), '".$periode."') PC
			, (STK + SDK + ITK + IDK + CT + CAP + CS + CB + DL + A) JUMLAH_TM
			, presensi.AMBIL_HARI_TIDAK_MASUK_KOREKSI(CAST(A.PEGAWAI_ID AS CHARACTER VARYING), '".$periode."') TM
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		LEFT JOIN 
		(
			SELECT
			PEGAWAI_ID,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'H'THEN JUMLAH END), 0) H,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'HT'THEN JUMLAH END), 0) HT,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'HPC'THEN JUMLAH END), 0) HPC,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'HTPC'THEN JUMLAH END), 0) HTPC,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'STK'THEN JUMLAH END), 0) STK,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'SDK'THEN JUMLAH END), 0) SDK,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'ITK'THEN JUMLAH END), 0) ITK,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'IDK'THEN JUMLAH END), 0) IDK,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'CT'THEN JUMLAH END), 0) CT,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'CAP'THEN JUMLAH END), 0) CAP,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'CS'THEN JUMLAH END), 0) CS,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'CB'THEN JUMLAH END), 0) CB,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'DL'THEN JUMLAH END), 0) DL,
			COALESCE (MAX (CASE WHEN KEHADIRAN = 'A'THEN JUMLAH END), 0) A
			FROM 
			(
				SELECT
				PEGAWAI_ID, KEHADIRAN, COUNT (KEHADIRAN) JUMLAH
				FROM presensi.P_REKAP_ABSENSI_KOREKSI('".$periode."', '')
				GROUP BY PEGAWAI_ID, KEHADIRAN
			) X
			GROUP BY PEGAWAI_ID
		) B ON A.PEGAWAI_ID = CAST(B.PEGAWAI_ID AS NUMERIC)
		LEFT JOIN presensi.PEGAWAI_JAM_KERJA_JENIS D ON A.PEGAWAI_ID = CAST(D.PEGAWAI_ID AS NUMERIC)
		LEFT JOIN presensi.JAM_KERJA_JENIS E ON D.JAM_KERJA_JENIS_ID = E.JAM_KERJA_JENIS_ID 
		WHERE 1 = 1
		"; 
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		$this->query = $str;
		// echo $str;exit();
		return $this->selectLimit($str,$limit,$from);
	}

	function getCountByParamsRekapTerlambatPulangKoreksi($paramsArray=array(), $periode, $statement='')
	{
		$str = "
		SELECT COUNT(1) AS ROWCOUNT 
		FROM
		(
			SELECT 
			A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
			, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
			, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT
			, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
			, JAB_RIW.ESELON_ID, PANG_RIW.PANGKAT_ID, PANG_RIW.TMT_PANGKAT, A.SATUAN_KERJA_ID
			FROM PEGAWAI A
			LEFT JOIN
			(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
			) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
			LEFT JOIN
			(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA, A.TMT_JABATAN, A.NAMA JABATAN_NAMA
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
			WHERE 1 = 1
		) A 
		WHERE 1 = 1 ".$statement;
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		$this->query = $str;
		$this->select($str); 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0;  
	}

} 
?>