<? 
/* *******************************************************************************************************
MODUL NAME 			: E LEARNING
FILE NAME 			: 
AUTHOR				: 
VERSION				: 1.0
MODIFICATION DOC	:
DESCRIPTION			: 
***************************************************************************************************** */

  /***
  * Entity-base class untuk mengimplementasikan tabel KontakPegawai.
  * 
  ***/
  include_once(APPPATH.'/models/Entity.php');
  
  class PegawaiInfo extends Entity{ 

	var $query;
    /**
    * Class constructor.
    **/
    function PegawaiInfo()
	{
      $this->Entity(); 
    }
	
    function selectByParams($paramsArray=array(),$limit=-1,$from=-1, $tahun, $statement='', $order='ORDER BY A.PEGAWAI_ID ASC')
	{
		$str = "
SELECT
		A.PEGAWAI_ID, A.NIP_LAMA, A.NIP_BARU
		, (CASE WHEN COALESCE(NULLIF(A.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE A.GELAR_DEPAN || ' ' END) || A.NAMA || (CASE WHEN COALESCE(NULLIF(A.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || A.GELAR_BELAKANG END) NAMA_LENGKAP
		, A.TEMPAT_LAHIR, A.TANGGAL_LAHIR, CASE A.JENIS_KELAMIN WHEN 'L' THEN 'Laki-Laki' ELSE 'Perempuan' END JENIS_KELAMIN_NAMA
		, A.ALAMAT, A.RT, A.RW, A.TELEPON, A.HP, A.NIK, A.NO_KK, A.NPWP
		, P1.PROPINSI_NAMA, P1.KABUPATEN_NAMA, P1.KECAMATAN_NAMA, P1.DESA_NAMA
		, PS.PEGAWAI_STATUS_NAMA, PS.PEGAWAI_KEDUDUKAN_NAMA
		, PANG_RIW.KODE PANGKAT_RIWAYAT_KODE, PANG_RIW.TMT_PANGKAT PANGKAT_RIWAYAT_TMT, PANG_RIW.PANGKAT_ID PANGKAT_RIWAYAT_PANGKAT_ID
		, GAJI_RIW.PANGKAT_ID GAJI_RIWAYAT_PANGKAT_ID
		, JAB_RIW.JENIS_JABATAN_ID JABATAN_RIWAYAT_JENIS_JABATAN_ID
		, JAB_RIW.JENIS_JABATAN_NAMA JABATAN_RIWAYAT_JENIS_JABATAN
		, JAB_RIW.TIPE_PEGAWAI_ID JABATAN_RIWAYAT_TIPE_PEGAWAI_ID
		, JAB_RIW.TIPE_PEGAWAI_NAMA JABATAN_RIWAYAT_TIPE_PEGAWAI_NAMA
		, JAB_RIW.JABATAN_NAMA JABATAN_RIWAYAT_NAMA
		, JAB_RIW.ESELON_NAMA JABATAN_RIWAYAT_ESELON
		, JAB_RIW.TMT_JABATAN JABATAN_RIWAYAT_TMT
		, JAB_RIW.JABATAN_FT_ID JABATAN_RIWAYAT_FT_ID
		, JAB_RIW.PANGKAT_ID_MIN JABATAN_RIWAYAT_PANGKAT_ID_MIN
		, JAB_RIW.PANGKAT_ID_MAX JABATAN_RIWAYAT_PANGKAT_ID_MAX
		, AMBIL_SATKER_NAMA_DYNAMIC(A.SATUAN_KERJA_ID) SATUAN_KERJA_NAMA, AMBIL_SATKER_INDUK(A.SATUAN_KERJA_ID) SATUAN_KERJA_INDUK
		, PF.PATH
		, DS.NAMA DIKLAT_STRUKTURAL_NAMA, DS.TANGGAL_STTPP DIKLAT_STRUKTURAL_TANGGAL
		, N.TAHUN PPK_TAHUN, PRESTASI_HASIL PPK_NILAI
		, PEN1.PENDIDIKAN_ID PENDIDIKAN_ID_CPNS, PEN1.PENDIDIKAN_NAMA PENDIDIKAN_NAMA_CPNS, PEN1.PENDIDIKAN_JURUSAN_NAMA PENDIDIKAN_JURUSAN_NAMA_CPNS
		, PEN2.PENDIDIKAN_ID PENDIDIKAN_ID_DIAKUI, PEN2.PENDIDIKAN_NAMA PENDIDIKAN_NAMA_DIAKUI, PEN2.PENDIDIKAN_JURUSAN_NAMA PENDIDIKAN_JURUSAN_NAMA_DIAKUI
		, JT.JABATAN_TUGAS_NAMA, JT.JABATAN_TUGAS_TMT
		, A.SATUAN_KERJA_ID
		FROM PEGAWAI A
		LEFT JOIN
		(
			SELECT A.PANGKAT_RIWAYAT_ID, B.KODE, A.TMT_PANGKAT, A.PANGKAT_ID
			FROM PANGKAT_RIWAYAT A
			LEFT JOIN PANGKAT B ON A.PANGKAT_ID = B.PANGKAT_ID
		) PANG_RIW ON A.PANGKAT_RIWAYAT_ID = PANG_RIW.PANGKAT_RIWAYAT_ID
		LEFT JOIN
		(
			SELECT A.GAJI_RIWAYAT_ID, A.PANGKAT_ID
			FROM GAJI_RIWAYAT A
		) GAJI_RIW ON A.GAJI_RIWAYAT_ID = GAJI_RIW.GAJI_RIWAYAT_ID
		LEFT JOIN
		(
			SELECT A.JABATAN_RIWAYAT_ID, COALESCE(A.ESELON_ID,99) ESELON_ID, B.NAMA ESELON_NAMA
			, A.TMT_JABATAN, A.NAMA JABATAN_NAMA, A.JENIS_JABATAN_ID
			, CASE A.JENIS_JABATAN_ID 
			WHEN '1' THEN 'Jabatan Struktural'
			WHEN '2' THEN 'Jabatan Pelaksana'
			WHEN '3' THEN 'Jabatan Fungsional Tertentu'
			END JENIS_JABATAN_NAMA
			, A.TIPE_PEGAWAI_ID
			, CASE A.TIPE_PEGAWAI_ID 
			WHEN '11' THEN 'Pejabat Eselon'
			WHEN '12' THEN 'Pelaksana'
			WHEN '21' THEN 'JFT Pendidikan'
			WHEN '22' THEN 'JFT Kesehatan'
			WHEN '23' THEN 'JFT Lainnya'
			END TIPE_PEGAWAI_NAMA
			, A.JABATAN_FT_ID
			, C.PANGKAT_ID_MIN
			, C.PANGKAT_ID_MAX
			FROM JABATAN_RIWAYAT A
			LEFT JOIN ESELON B ON A.ESELON_ID = B.ESELON_ID
			LEFT JOIN JABATAN_FT AS C ON A.JABATAN_FT_ID = C.JABATAN_FT_ID
		) JAB_RIW ON A.JABATAN_RIWAYAT_ID = JAB_RIW.JABATAN_RIWAYAT_ID
		LEFT JOIN 
		(
			SELECT PEGAWAI_ID, PATH FROM PEGAWAI_FILE_DATA WHERE RIWAYAT_TABLE = 'PEGAWAI' AND RIWAYAT_ID = 1
		) PF ON PF.PEGAWAI_ID = A.PEGAWAI_ID
		LEFT JOIN DIKLAT_STRUKTURAL_TERAKHIR DS ON A.PEGAWAI_ID = DS.PEGAWAI_ID
		LEFT JOIN
		(
			SELECT A.PEGAWAI_STATUS_ID, A.PEGAWAI_ID, A.STATUS_PEGAWAI_ID, B.NAMA PEGAWAI_STATUS_NAMA
			, A.TMT PEGAWAI_KEDUDUKAN_TMT, C.NAMA PEGAWAI_KEDUDUKAN_NAMA
			FROM PEGAWAI_STATUS A
			INNER JOIN STATUS_PEGAWAI B ON A.STATUS_PEGAWAI_ID = B.STATUS_PEGAWAI_ID
			INNER JOIN STATUS_PEGAWAI_KEDUDUKAN C ON A.STATUS_PEGAWAI_KEDUDUKAN_ID = C.STATUS_PEGAWAI_KEDUDUKAN_ID
		) PS ON A.PEGAWAI_STATUS_ID = PS.PEGAWAI_STATUS_ID
		LEFT JOIN
		(
			SELECT A.PEGAWAI_ID
			, A.PROPINSI_ID, PROP.NAMA PROPINSI_NAMA, A.KABUPATEN_ID, KAB.NAMA KABUPATEN_NAMA, A.KECAMATAN_ID, KEC.NAMA KECAMATAN_NAMA, A.DESA_ID, KEL.NAMA DESA_NAMA
			FROM PEGAWAI A
			LEFT JOIN (SELECT PROPINSI_ID, NAMA FROM PROPINSI) PROP ON PROP.PROPINSI_ID = A.PROPINSI_ID
			LEFT JOIN (SELECT PROPINSI_ID, KABUPATEN_ID, NAMA FROM KABUPATEN) KAB ON KAB.PROPINSI_ID = A.PROPINSI_ID AND KAB.KABUPATEN_ID = A.KABUPATEN_ID
			LEFT JOIN (SELECT PROPINSI_ID, KABUPATEN_ID, KECAMATAN_ID, NAMA FROM KECAMATAN) KEC ON KEC.PROPINSI_ID = A.PROPINSI_ID AND KEC.KABUPATEN_ID = A.KABUPATEN_ID AND KEC.KECAMATAN_ID = A.KECAMATAN_ID
			LEFT JOIN (SELECT PROPINSI_ID, KABUPATEN_ID, KECAMATAN_ID, KELURAHAN_ID, NAMA FROM KELURAHAN) KEL ON KEL.PROPINSI_ID = A.PROPINSI_ID AND KEL.KABUPATEN_ID = A.KABUPATEN_ID AND KEL.KECAMATAN_ID = A.KECAMATAN_ID AND KEL.KELURAHAN_ID = A.DESA_ID
			WHERE 1 = 1
		) P1 ON P1.PEGAWAI_ID = A.PEGAWAI_ID
		LEFT JOIN
		(
			SELECT A.PEGAWAI_ID, A.TAHUN, PRESTASI_HASIL, JUMLAH_NILAI, RATA_NILAI 
			FROM PENILAIAN_SKP A WHERE 1=1 AND A.TAHUN = '".$tahun."'
		) N ON A.PEGAWAI_ID = N.PEGAWAI_ID
		LEFT JOIN
		(
			SELECT A.PEGAWAI_ID, A.PENDIDIKAN_NAMA, A.PENDIDIKAN_JURUSAN_NAMA, A.PENDIDIKAN_ID
			FROM PENDIDIKAN_RIWAYAT_DATA A
			WHERE STATUS_PENDIDIKAN = '1' AND (COALESCE(NULLIF(A.STATUS, ''), NULL) IS NULL OR A.STATUS = '2')
		) PEN1 ON A.PEGAWAI_ID = PEN1.PEGAWAI_ID
		LEFT JOIN
		(
			SELECT A.PENDIDIKAN_RIWAYAT_ID, A.PENDIDIKAN_NAMA, A.PENDIDIKAN_JURUSAN_NAMA, A.PENDIDIKAN_ID
			FROM PENDIDIKAN_RIWAYAT_DATA A
			WHERE STATUS_PENDIDIKAN = '2' AND (COALESCE(NULLIF(A.STATUS, ''), NULL) IS NULL OR A.STATUS = '2')
		) PEN2 ON A.PENDIDIKAN_RIWAYAT_ID = PEN2.PENDIDIKAN_RIWAYAT_ID
		LEFT JOIN
		(
			SELECT PEGAWAI_ID, NAMA JABATAN_TUGAS_NAMA, TMT_JABATAN JABATAN_TUGAS_TMT
			FROM JABATAN_TAMBAHAN A
			WHERE (COALESCE(NULLIF(A.STATUS, ''), NULL) IS NULL OR A.STATUS = '2')
			AND EXISTS
			(
				SELECT 1
				FROM
				(
					SELECT PEGAWAI_ID, MAX(TMT_JABATAN) TMT_JABATAN FROM JABATAN_TAMBAHAN X 
					WHERE (COALESCE(NULLIF(X.STATUS, ''), NULL) IS NULL OR X.STATUS = '2')
					GROUP BY PEGAWAI_ID
				) X
				WHERE A.PEGAWAI_ID = X.PEGAWAI_ID AND A.TMT_JABATAN = X.TMT_JABATAN
			)
		) JT ON A.PEGAWAI_ID = JT.PEGAWAI_ID
		WHERE 1 = 1
		"; 

		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
			
		$str .= $statement."  ".$order;
		$this->query = $str;

		// echo $str;exit;
		return $this->selectLimit($str,$limit,$from); 
		
    }
	 
    function getCountByParams($paramsArray=array(), $statement='')
	{
		$str = "SELECT COUNT(A.BAHASA_ID) AS ROWCOUNT 
				FROM BAHASA A
				WHERE 1 = 1 ".$statement; 
		while(list($key,$val)=each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		$this->select($str); 
		if($this->firstRow()) 
			return $this->getField("ROWCOUNT"); 
		else 
			return 0; 
    }

  } 
?>