<? 
/* *******************************************************************************************************
MODUL NAME 			: MTSN LAWANG
FILE NAME 			: 
AUTHOR				: 
VERSION				: 1.0
MODIFICATION DOC	:
DESCRIPTION			: 
***************************************************************************************************** */

  /***
  * Entity-base class untuk mengimplementasikan tabel kategori.
  * 
  ***/
  // include_once('Entity.php');
  include_once(APPPATH.'/models/Entity.php');
  include_once("functions/date.func.php");
  
  class CetakPdf extends Entity{ 

	 var $query;
  	var $id;
    /**
    * Class constructor.
    **/
    function CetakPdf()
	{
      $this->Entity(); 
    }

	function selectByParamsKenaikanGajiBerkala($paramsArray=array(),$limit=-1,$from=-1, $statement='',$order=' ')
	{
		$str = "
		SELECT
			CONCAT(SPLIT_PART(SK.NOMOR, '/', 1), '/', SPLIT_PART(SK.NOMOR, '/', 2), '.', CAST(A.NOMOR_URUT AS TEXT), '/', SPLIT_PART(SK.NOMOR, '/', 3), '/', SPLIT_PART(SK.NOMOR, '/', 4)) NOMOR_SURAT
			, (CASE WHEN COALESCE(NULLIF(P.GELAR_DEPAN,'') , NULL ) IS NULL THEN '' ELSE P.GELAR_DEPAN || ' ' END) || P.NAMA || (CASE WHEN COALESCE(NULLIF(P.GELAR_BELAKANG,'') , NULL ) IS NULL THEN '' ELSE '' || P.GELAR_BELAKANG END) NAMA_LENGKAP
			, P.NIP_BARU, PR1.PANGKAT_KODE PANGKAT_DASAR_KODE, PR1.PANGKAT_NAMA PANGKAT_DASAR_NAMA, AMBIL_SATKER_NAMA_DETIL(A.SATUAN_KERJA_ID) PEGAWAI_SATUAN_KERJA_NAMA_DETIL
			, PR1.PEJABAT_PENETAP_NAMA PANGKAT_DASAR_PEJABAT_PENETAP, PR1.TANGGAL_SK PANGKAT_DASAR_TANGGAL_SK, PR1.NO_SK PANGKAT_DASAR_NO_SK
			, PR1.GAJI_POKOK PANGKAT_DASAR_GAJI
			, PR1.MASA_KERJA_TAHUN PANGKAT_DASAR_MASA_KERJA_TAHUN, PR1.MASA_KERJA_BULAN PANGKAT_DASAR_MASA_KERJA_BULAN, PR1.TMT_SK PANGKAT_DASAR_TMT
			, COALESCE(PR2.TANGGAL_SK, A.TANGGAL_BARU) PANGKAT_BARU_TANGGAL_SK
			, COALESCE(PR2.GAJI_POKOK, A.GAJI_BARU) PANGKAT_BARU_GAJI, COALESCE(PR2.MASA_KERJA_TAHUN, A.MASA_KERJA_TAHUN_BARU) PANGKAT_BARU_MASA_KERJA_TAHUN
			, COALESCE(PR2.MASA_KERJA_BULAN, A.MASA_KERJA_BULAN_BARU) PANGKAT_BARU_MASA_KERJA_BULAN, COALESCE(PR2.TMT_SK, A.TMT_BARU) PANGKAT_BARU_TMT
			, A.HUKUMAN_RIWAYAT_ID, HK.TMT_BERIKUT_GAJI, HK.NO_SK HUKUMAN_NO_SK, HK.TMT_SK HUKUMAN_TMT_SK
			, AMBIL_SATKER_NAMA_JABATAN_INDUK(A.SATUAN_KERJA_ID) SATUAN_KERJA_KEPALA_INDUK
		FROM KENAIKAN_GAJI_BERKALA A
		INNER JOIN PEGAWAI P ON A.PEGAWAI_ID = P.PEGAWAI_ID
		LEFT JOIN PERSURATAN.SURAT_KELUAR_BKD SK ON A.SURAT_KELUAR_BKD_ID = SK.SURAT_KELUAR_BKD_ID
		INNER JOIN GAJI_RIWAYAT_DATA PR1 ON A.GAJI_RIWAYAT_LAMA_ID = PR1.GAJI_RIWAYAT_ID
		LEFT JOIN GAJI_RIWAYAT_DATA PR2 ON A.GAJI_RIWAYAT_BARU_ID = PR2.GAJI_RIWAYAT_ID
		LEFT JOIN
		(
			SELECT 	
				A.HUKUMAN_ID, A.PEGAWAI_ID, B.NAMA TINGKAT_HUKUMAN_NAMA, C.NAMA JENIS_HUKUMAN_NAMA
				, A.NO_SK, A.TANGGAL_SK, A.TMT_SK, A.TMT_BERIKUT_GAJI
				, CONCAT(B.NAMA, ' : ', C.NAMA) KETERANGAN_HUKUMAN_INFO
			FROM HUKUMAN A
			LEFT JOIN TINGKAT_HUKUMAN B ON B.TINGKAT_HUKUMAN_ID = A.TINGKAT_HUKUMAN_ID
			LEFT JOIN JENIS_HUKUMAN C ON C.JENIS_HUKUMAN_ID = A.JENIS_HUKUMAN_ID
		) HK ON A.HUKUMAN_RIWAYAT_ID = HK.HUKUMAN_ID
		WHERE 1 = 1
		"; 
		
		foreach ($paramsArray as $key => $val)
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$order;
		//echo $str;exit;
		$this->query = $str;
		return $this->selectLimit($str,$limit,$from); 
    }
	
  } 
?>